### PR TITLE
Update list of mocked UUIDs to be valid UUIDv4

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by fblackburn1** [comment]
Well see !! From what I understand it's only the `4` at the beginning of the third section that are mandatory? In this case I would prefer to have this kind of change
```diff
- 00000000-0000-0000-0000-000000000001
+ 00000000-0000-4000-0000-000000000001
```
Instead of 
```diff
- 00000000-0000-0000-0000-000000000001
+ 00000000-0000-4c1c-ad1c-000000000001
```

That being said, these values are considered as *legacy* (we probably should write it somewhere in the mock...), in a way that if you cannot do what you want with them, then add yours in your test suite (ex: [wazo-webhookd](https://github.com/wazo-platform/wazo-webhookd/blob/master/integration_tests/suite/helpers/base.py#L83)). 
With the time, we had concluded that adding default values in the mock are just too painful to maintain and a wrong thing to too. Each project should setup it's mock as it want.
Because for now, changing these values will break probably 99% of our tests. And I would like more to spend time to change the initialization process (like wazo-webhookd) to remove these values than changing the uuid for a valid uuid4

**Comment by tranchitella** [comment]
@fblackburn1 

Hello, thank your feedback; my issue is that these are not valid UUIDv4:

```
>>> from uuid import UUID
>>> UUID('00000000-0000-4000-0000-000000000001').version is None
True
>>> UUID('00000000-0000-4c1c-ad1c-000000000001').version
4
```

With a valid UUIDv4 wazo-router-confd works perfectly, the mock is very useful; I can write my own mock if you think it is a better solution, though. Just wanted to contribute with a fix.

**Comment by fblackburn1** [comment]
> @fblackburn1
> 
> Hello, thank your feedback; my issue is that these are not valid UUIDv4:
> 
> ```
> >>> from uuid import UUID
> >>> UUID('00000000-0000-4000-0000-000000000001').version is None
> True
> >>> UUID('00000000-0000-4c1c-ad1c-000000000001').version
> 4
> ```
> 
> With a valid UUIDv4 wazo-router-confd works perfectly, the mock is very useful; I can write my own mock if you think it is a better solution, though. Just wanted to contribute with a fix.

Wow you right, it seems there are also a constraint on the first value of the fourth section to be [89ab] ... :rofl: (according the regex [from this thread](https://stackoverflow.com/a/19989922) )

But IMO, yes you should insert your own values on your test setup using this mock methods

**Comment by tranchitella** [comment]
@fblackburn1 ack, creating my own mocked data as you suggested.

**Pull request closed without merging**
